### ISSUE TITLE
Configuration done but no data appears

### ISSUE THREAD

**Issue by anthonytison** [Gatsbylius/gatsbylius-starter#14]
Hi!! 

I'm very excited by the work you've done with Gatbsy & Sylius and i'd really like to use it for a current project.

So I just finished installing Gatsbylius on my local machine, configured everything according to the ReadMe and set the right Sylius url but it doesn't seem to work. So far, no data appears. 

I checked if i could get datas from the graphQL interface but nothing comes up. The homepage is also empty of datas. 

I hope you will be able to help me with that.

**Comment by gkueny** [comment]
Hi, 

I just try a fresh install & all work for me.

Can you confirm what you did to set up the project? Do you use your own Sylius or our demo https://api.gatsbylius.com ?

For the record, here's the one I did : 

```shell
gatsby new gatsbylius-starter https://github.com/Gatsbylius/gatsbylius-starter

cd gatsbylius-starter

cp .env .env.local

yarn start
```

**Comment by anthonytison** [comment]
I'm using my own Sylius and i added the ShopApiBundle (which wasn't installed). 

I tested the Api configuration by trying to get a list of products (GET https://mylocaldomain/shop-api/product-latest) via Postman and it worked.

The local Sylius url has been configured in .env.local instead of your distant url.

I don't know if it will be useful but this is what i got when i run `yarn start`

<pre>success open and validate gatsby-configs - 0.059s
success load plugins - 1.111s
success onPreInit - 0.019s
success initialize cache - 0.009s
success copy gatsby files - 0.128s
success onPreBootstrap - 0.014s
success createSchemaCustomization - 0.006s

 ERROR #11321  PLUGIN

"gatsby-source-sylius" threw an error while running the sourceNodes lifecycle:

unable to verify the first certificate



  RequestError: unable to verify the first certificate
  
  - request-as-event-emitter.js:178 ClientRequest.<anonymous>
    [gatsbylius-starter]/[gatsby-source-sylius]/[got]/source/request-as-event-emitter.js:178:14
  
  - index.js:37 ClientRequest.origin.emit
    [gatsbylius-starter]/[@szmarczak]/http-timer/source/index.js:37:11
  
  - destroy.js:84 emitErrorNT
    internal/streams/destroy.js:84:8
  
  - task_queues.js:84 processTicksAndRejections
    internal/process/task_queues.js:84:21
  
  - From previous event:
  
  - api-runner-node.js:258 runAPI
    [gatsbylius-starter]/[gatsby]/dist/utils/api-runner-node.js:258:22
  
  - api-runner-node.js:375 Promise.catch.decorateEvent.pluginName
    [gatsbylius-starter]/[gatsby]/dist/utils/api-runner-node.js:375:15
  
  - From previous event:
  
  - api-runner-node.js:374 
    [gatsbylius-starter]/[gatsby]/dist/utils/api-runner-node.js:374:12
  
  - timers.js:456 processImmediate
    internal/timers.js:456:21
  
  - From previous event:
  
  - api-runner-node.js:368 
    [gatsbylius-starter]/[gatsby]/dist/utils/api-runner-node.js:368:11
  
  - From previous event:
  
  - api-runner-node.js:275 module.exports
    [gatsbylius-starter]/[gatsby]/dist/utils/api-runner-node.js:275:12
  
  - source-nodes.js:84 Object._default [as default]
    [gatsbylius-starter]/[gatsby]/dist/utils/source-nodes.js:84:36
  
  - index.js:386 module.exports
    [gatsbylius-starter]/[gatsby]/dist/bootstrap/index.js:386:49
  
  - develop-process.js:433 async module.exports
    [gatsbylius-starter]/[gatsby]/dist/commands/develop-process.js:433:7
  

warn The gatsby-source-sylius plugin has generated no Gatsby nodes. Do you need it?
success source and transform nodes - 0.162s
success building schema - 0.266s
success createPages - 0.016s
success createPagesStatefully - 0.071s
success onPreExtractQueries - 0.001s
success update schema - 0.022s
success extract queries from components - 0.397s
warn The GraphQL query in the non-page component "/Applications/MAMP/htdocs/GTAB/sandbox/gatsbylius-starter/src/templates/product.js"
warn The GraphQL query in the non-page component "/Applications/MAMP/htdocs/GTAB/sandbox/gatsbylius-starter/src/templates/category.js"
Exported queries are only executed for Page components. It's possible you're
trying to create pages in your gatsby-node.js and that's failing for some
reason.

If the failing component(s) is a regular component and not intended to be a page
component, you generally want to use a <StaticQuery> (https://gatsbyjs.org/docs/static-query)
instead of exporting a page query.

If you're more experienced with GraphQL, you can also export GraphQL
fragments from components and compose the fragments in the Page component
query and pass data down into the child component — https://graphql.org/learn/queries/#fragments
success write out requires - 0.024s
success write out redirect data - 0.002s
success Build manifest and related icons - 0.110s
success onPostBootstrap - 0.115s
⠀
info bootstrap finished - 5.936s
⠀
success run page queries - 0.024s - 6/6 254.89/s
⠀
You can now view gatsby-starter-sylius in the browser.
⠀
  http://localhost:8000/
⠀
View GraphiQL, an in-browser IDE, to explore your site's data and schema
⠀
  http://localhost:8000/___graphql
⠀
Note that the development build is not optimized.
To create a production build, use gatsby build
⠀
success Building development bundle - 9.141s</pre>

**Comment by gkueny** [comment]
> "gatsby-source-sylius" threw an error while running the sourceNodes lifecycle:
> unable to verify the first certificate

it looks like the ssl certificate is no good. 
If I remember correctly, self-signed certificates don't work well. Have you tried without https ?

**Comment by anthonytison** [comment]
I don't have the SSL error anymore but i still get an error 
<pre>"gatsby-source-sylius" threw an error while running the sourceNodes lifecycle:

Response code 404 (Not Found)</pre>

**Comment by gkueny** [comment]
Do you follow https://github.com/Sylius/ShopApiPlugin#installation instructions & fix configuration issues (https://github.com/Sylius/ShopApiPlugin/issues/241#issuecomment-542240749) ?

**Comment by anthonytison** [comment]
Yes i already did the ShopApiPlugin installation. I just skipped the installation of `nelmio/NelmioCorsBundle`

Like i said earlier i can call `/shop-api/product-latest` via postman and i get a list of products. 

Is there a way to get logs when the script gets datas from source ?

**Comment by anthonytison** [comment]
Ok so i went through your import script and find why i got a 404 error.

In the file `syliusClient.js` at line 31, you try to get taxons with parent name `category`. Unfortunately, i don't have any taxon called category so it results with a 404 error. Would it be possible not having this pre-defined parent taxon ?

I just added the new taxon `category` as a parent and it worked but my products don't have images yet so i have new errors during the process. I guess it would be nice to check if we have at least one image uploaded for a product. Right it results of errors in the console and a broken front page.

**Comment by gkueny** [comment]
> In the file syliusClient.js at line 31, you try to get taxons with parent name category. Unfortunately, i don't have any taxon called category so it results with a 404 error. Would it be possible not having this pre-defined parent taxon ?

We should make it configurable https://github.com/Gatsbylius/Gatsbylius/tree/master/packages/gatsby-source-sylius yes (like Sylius url)

> my products don't have images yet so i have new errors during the process

We do not handle this case. I will implement that

Thanks, for your investigation, I will publish fix for these issues

**Comment by anthonytison** [comment]
Sounds perfect. Thx so much

**Comment by gkueny** [comment]
Should be fixed on master.
